name: Flask CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Run app inside Docker container
      - name: Run Flask app in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app python:3.9 bash -c "
            pip install -r requirements.txt &&
            python app.py
          "
